import "./globals.scss";

import { Lato } from "next/font/google";

const lato = Lato({ weight: "400", subsets: ['latin'] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.className} rootLayout`}>{children}</body>
    </html>
  );
}
